num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("Number 1 + Number2 = ",num1+num2)
print("Number 1 - Number2 = ",num1-num2)
print("Number 1 * Number2 = ",num1*num2)
print("Number 1 / Number2 = ",num1/num2)
print("Number 1 % Number2 = ",num1%num2)
print("Number 1 // Number2 = ",num1//num2)
print("Number 1 ** Number2 = ",num1**num2)